# SPDX-License-Identifier: GPL-3.0-or-later
"""Public-channel auto-update façade. Implementation lives in update_* modules."""

from __future__ import annotations

from core.update_fetch import (
    _asset_name,
    _asset_url,
    app_display_name,
    check_for_update,
    download_bundle,
    local_version,
    public_download_url,
    restart_hint,
    update_channel,
    updates_dir,
)
from core.update_install import (
    apply_update,
    install_bundle,
    install_flatpak_bundle,
    install_native_tarball,
    launch_check_terminal,
    launch_update_terminal,
    open_terminal_script,
    write_check_report_script,
    write_update_script,
)
from core.update_url import (
    APP_ID,
    ASSET_NAME,
    Channel,
    DIRECT_URL,
    FLATPAK_ASSET,
    FLATPAK_DIRECT,
    FLATPAK_PUBLIC_RELEASES,
    FLATPAK_RELEASES_API,
    FLATPAK_RELEASES_LATEST_API,
    FLATPAK_RELEASES_LIST_API,
    NATIVE_ASSET_TMPL,
    NATIVE_DIRECT,
    NATIVE_PUBLIC_RELEASES,
    NATIVE_RELEASES_API,
    NATIVE_RELEASES_LATEST_API,
    NATIVE_RELEASES_LIST_API,
    PUBLIC_RELEASES,
    RELEASES_API,
    TAG_PREFIX,
    UpdateError,
    _require_allowed_url,
    parse_semver,
    version_from_release,
)

__all__ = [
    "APP_ID",
    "ASSET_NAME",
    "Channel",
    "DIRECT_URL",
    "FLATPAK_ASSET",
    "FLATPAK_DIRECT",
    "FLATPAK_PUBLIC_RELEASES",
    "FLATPAK_RELEASES_API",
    "FLATPAK_RELEASES_LATEST_API",
    "FLATPAK_RELEASES_LIST_API",
    "NATIVE_ASSET_TMPL",
    "NATIVE_DIRECT",
    "NATIVE_PUBLIC_RELEASES",
    "NATIVE_RELEASES_API",
    "NATIVE_RELEASES_LATEST_API",
    "NATIVE_RELEASES_LIST_API",
    "PUBLIC_RELEASES",
    "RELEASES_API",
    "TAG_PREFIX",
    "UpdateError",
    "_asset_name",
    "_asset_url",
    "_require_allowed_url",
    "app_display_name",
    "apply_update",
    "check_for_update",
    "download_bundle",
    "install_bundle",
    "install_flatpak_bundle",
    "install_native_tarball",
    "launch_check_terminal",
    "launch_update_terminal",
    "local_version",
    "open_terminal_script",
    "parse_semver",
    "public_download_url",
    "restart_hint",
    "update_channel",
    "updates_dir",
    "version_from_release",
    "write_check_report_script",
    "write_update_script",
]
